// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamA.PurchaseOrders.Data;

namespace TeamA.PurchaseOrders.Data.Migrations
{
    [DbContext(typeof(PurchaseOrdersDb))]
    partial class PurchaseOrdersDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamA.PurchaseOrders.Models.Dtos.PaymentInformationDto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardCVC")
                        .IsRequired();

                    b.Property<DateTime>("CardExpiry");

                    b.Property<string>("CardName")
                        .IsRequired();

                    b.Property<string>("CardNumber")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("PaymentInformation");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Models.Dtos.ProductDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrandId");

                    b.Property<string>("BrandName");

                    b.Property<int>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Ean")
                        .IsRequired();

                    b.Property<bool?>("ExpectedRestock");

                    b.Property<int>("ExternalId");

                    b.Property<bool>("InStock");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Models.Dtos.PurchaseOrderDto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<int>("ExternalID");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("PaymentInformationID");

                    b.Property<string>("Postcode")
                        .IsRequired();

                    b.Property<int>("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<double>("ProductPrice");

                    b.Property<Guid>("PurchasedBy");

                    b.Property<DateTime?>("PurchasedOn")
                        .IsRequired();

                    b.Property<int>("Quantity");

                    b.Property<string>("Source");

                    b.Property<Guid>("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("PaymentInformationID");

                    b.HasIndex("StatusID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Models.Dtos.PurchaseStatusDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PurchaseStatus");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Models.Dtos.PurchaseOrderDto", b =>
                {
                    b.HasOne("TeamA.PurchaseOrders.Models.Dtos.PaymentInformationDto", "PaymentInformation")
                        .WithMany()
                        .HasForeignKey("PaymentInformationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TeamA.PurchaseOrders.Models.Dtos.PurchaseStatusDto", "PurchaseStatus")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
