// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamA.PurchaseOrders.Data;

namespace TeamA.PurchaseOrders.Data.Migrations
{
    [DbContext(typeof(PurchaseOrdersDb))]
    partial class PurchaseOrdersDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamA.PurchaseOrders.Data.Models.PaymentInformation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CVC")
                        .IsRequired();

                    b.Property<string>("CardNumber")
                        .IsRequired();

                    b.Property<string>("CardholderName")
                        .IsRequired();

                    b.Property<string>("ExpiryDate")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("PaymentInformation");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Data.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cost");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("PaymentInformationID");

                    b.Property<Guid>("ProductID");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<Guid>("PurchasedBy");

                    b.Property<DateTime?>("PurchasedOn")
                        .IsRequired();

                    b.Property<int>("Quantity");

                    b.Property<Guid>("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("PaymentInformationID");

                    b.HasIndex("StatusID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Data.Models.PurchaseStatus", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("PurchaseStatus");
                });

            modelBuilder.Entity("TeamA.PurchaseOrders.Data.Models.PurchaseOrder", b =>
                {
                    b.HasOne("TeamA.PurchaseOrders.Data.Models.PaymentInformation", "PaymentInformation")
                        .WithMany()
                        .HasForeignKey("PaymentInformationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TeamA.PurchaseOrders.Data.Models.PurchaseStatus", "PurchaseStatus")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
